# Generated by Django 4.2.1 on 2023-05-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='toilet',
            table='capstone_toilet',
        ),
    ]
