# Generated by Django 4.1.5 on 2023-05-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0002_alter_toilet_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toilet',
            options={'verbose_name': '화장실', 'verbose_name_plural': '화장실'},
        ),
        migrations.AddField(
            model_name='toilet',
            name='area',
            field=models.CharField(max_length=50, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='bellYN',
            field=models.CharField(default='N', max_length=10, verbose_name='비상벨 여부'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='using',
            field=models.CharField(max_length=50, null=True, verbose_name='주용도'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='way',
            field=models.CharField(max_length=100, null=True, verbose_name='처리방식'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(max_length=150, verbose_name='소재지'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='name',
            field=models.CharField(max_length=50, verbose_name='명칭'),
        ),
    ]
