# Generated by Django 4.1.5 on 2023-05-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0003_alter_toilet_options_toilet_area_toilet_bellyn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='address',
            field=models.CharField(max_length=150, null=True, verbose_name='소재지'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='bellYN',
            field=models.CharField(default='여', max_length=10, null=True, verbose_name='비상벨 여부'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='명칭'),
        ),
    ]
