# Generated by Django 4.2.1 on 2023-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0004_alter_toilet_address_alter_toilet_bellyn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='cleanliness',
            field=models.FloatField(default=0, verbose_name='청결도'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='diaper_change',
            field=models.CharField(max_length=10, null=True, verbose_name='기저귀 교환대'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='for_children',
            field=models.CharField(max_length=10, null=True, verbose_name='아동 전용'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='for_disabled',
            field=models.CharField(default='N', max_length=10, null=True, verbose_name='장애인 전용'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='hand_sanitizer',
            field=models.CharField(max_length=10, null=True, verbose_name='손 세정제'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='separate',
            field=models.CharField(default='Y', max_length=10, null=True, verbose_name='남녀분리'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='toilet_count',
            field=models.IntegerField(null=True, verbose_name='좌변기 갯수'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='toilet_paper',
            field=models.CharField(default='Y', max_length=10, null=True, verbose_name='휴지'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='washstand',
            field=models.CharField(default='Y', max_length=10, null=True, verbose_name='세면대'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='women_safe',
            field=models.CharField(max_length=10, null=True, verbose_name='여성 안심 화장실'),
        ),
    ]
