# Generated by Django 4.2.1 on 2023-06-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toilet', '0005_toilet_cleanliness_toilet_diaper_change_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('user_name', models.CharField(max_length=50, verbose_name='사용자 이름')),
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('toilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toilet.toilet')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'db_table': 'capstone_review',
            },
        ),
    ]
